### PR TITLE
Feature/simplification

### PR DESCRIPTION
**Pull request by Daniel-KM**
Hi,
I fixed various points on the module and simplified the configuration (automatic detection of the default page).
In the next days, I 'll publish a new version of Clean Url that is compatible with this module and can create full custom url with a root site, fixing omeka/omeka-s#870 and fixing #2 .

### CODE REVIEW

**Comment by hafizchin** [comment]
Hi Daniel,

Thanks for the enhancements!

**Comment by hafizchin** [comment]
Hi,

looks like you removed the logic that maps routes that are defined in the config file. Please see latest commit

**Comment by Daniel-KM** [comment]
Yes, I removed them. I'm not sure if it is usefull, since there is another check of dynamic routes just below.

**Comment by hafizchin** [comment]
not all routes are created dynamically. for example, the [Collecting](https://omeka.org/s/modules/Collecting/) module uses routes that are defined in the config file.

**Pull request merged**
